<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * API for applications: external references on emails and conversations, Idempotency-Key storage, replies
 * without a user (an application acting for itself).
 */
final class Version20260928145211 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'externalRef on emails and conversations, idempotency keys, email sender optional';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE idempotency_key (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, scope VARCHAR(120) NOT NULL, idempotency_key VARCHAR(190) NOT NULL, request_hash VARCHAR(64) NOT NULL, response_status INT DEFAULT NULL, response_body TEXT DEFAULT NULL, response_content_type VARCHAR(120) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7FD1C1478B8E8428 ON idempotency_key (created_at)');
        $this->addSql('CREATE UNIQUE INDEX uniq_idempotency_scope_key ON idempotency_key (scope, idempotency_key)');
        $this->addSql('ALTER TABLE conversation ADD external_ref VARCHAR(190) DEFAULT NULL');
        $this->addSql('CREATE INDEX IDX_8A8E26E966EC35CCB445906B ON conversation (mailbox_id, external_ref)');
        $this->addSql('ALTER TABLE email ADD external_ref VARCHAR(190) DEFAULT NULL');
        $this->addSql('ALTER TABLE email ALTER sender_id DROP NOT NULL');
        $this->addSql('CREATE INDEX IDX_E7927C74B445906B ON email (external_ref)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE idempotency_key');
        $this->addSql('DROP INDEX IDX_8A8E26E966EC35CCB445906B');
        $this->addSql('ALTER TABLE conversation DROP external_ref');
        $this->addSql('DROP INDEX IDX_E7927C74B445906B');
        $this->addSql('ALTER TABLE email DROP external_ref');
        $this->addSql('ALTER TABLE email ALTER sender_id SET NOT NULL');
    }
}
