<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260924054612 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE application (id UUID NOT NULL, name VARCHAR(120) NOT NULL, description TEXT DEFAULT NULL, token_hash VARCHAR(64) NOT NULL, token_hint VARCHAR(16) NOT NULL, can_impersonate BOOLEAN NOT NULL, allowed_origins JSON NOT NULL, enabled BOOLEAN NOT NULL, last_used_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_by VARCHAR(180) DEFAULT NULL, updated_by VARCHAR(180) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A45BDDC1B3BC57DA ON application (token_hash)');
        $this->addSql('CREATE TABLE email (id UUID NOT NULL, recipients_to JSON NOT NULL, recipients_cc JSON NOT NULL, recipients_bcc JSON NOT NULL, subject VARCHAR(255) NOT NULL, html_body TEXT NOT NULL, status VARCHAR(16) NOT NULL, error_message TEXT DEFAULT NULL, sent_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_by VARCHAR(180) DEFAULT NULL, updated_by VARCHAR(180) DEFAULT NULL, sender_id UUID NOT NULL, application_id UUID DEFAULT NULL, template_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E7927C747B00651C ON email (status)');
        $this->addSql('CREATE INDEX IDX_E7927C74F624B39D ON email (sender_id)');
        $this->addSql('CREATE INDEX IDX_E7927C743E030ACD ON email (application_id)');
        $this->addSql('CREATE INDEX IDX_E7927C745DA0FB8 ON email (template_id)');
        $this->addSql('CREATE TABLE email_template (id UUID NOT NULL, name VARCHAR(150) NOT NULL, description TEXT DEFAULT NULL, default_subject VARCHAR(255) DEFAULT NULL, project_data JSON DEFAULT NULL, html TEXT NOT NULL, shared BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_by VARCHAR(180) DEFAULT NULL, updated_by VARCHAR(180) DEFAULT NULL, owner_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9C0600CA7E3C61F9 ON email_template (owner_id)');
        $this->addSql('CREATE TABLE email_template_version (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, action VARCHAR(8) NOT NULL, logged_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, object_id VARCHAR(64) DEFAULT NULL, object_class VARCHAR(191) NOT NULL, version INT NOT NULL, data JSON DEFAULT NULL, username VARCHAR(191) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX email_template_version_lookup_idx ON email_template_version (object_class, object_id, version)');
        $this->addSql('CREATE TABLE "user" (id UUID NOT NULL, email VARCHAR(180) NOT NULL, first_name VARCHAR(100) DEFAULT NULL, last_name VARCHAR(100) DEFAULT NULL, roles JSON NOT NULL, password VARCHAR(255) DEFAULT NULL, source VARCHAR(16) NOT NULL, ldap_dn VARCHAR(512) DEFAULT NULL, ldap_synced_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, enabled BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_by VARCHAR(180) DEFAULT NULL, updated_by VARCHAR(180) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');
        $this->addSql('ALTER TABLE email ADD CONSTRAINT FK_E7927C74F624B39D FOREIGN KEY (sender_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE email ADD CONSTRAINT FK_E7927C743E030ACD FOREIGN KEY (application_id) REFERENCES application (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE email ADD CONSTRAINT FK_E7927C745DA0FB8 FOREIGN KEY (template_id) REFERENCES email_template (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE email_template ADD CONSTRAINT FK_9C0600CA7E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE email DROP CONSTRAINT FK_E7927C74F624B39D');
        $this->addSql('ALTER TABLE email DROP CONSTRAINT FK_E7927C743E030ACD');
        $this->addSql('ALTER TABLE email DROP CONSTRAINT FK_E7927C745DA0FB8');
        $this->addSql('ALTER TABLE email_template DROP CONSTRAINT FK_9C0600CA7E3C61F9');
        $this->addSql('DROP TABLE application');
        $this->addSql('DROP TABLE email');
        $this->addSql('DROP TABLE email_template');
        $this->addSql('DROP TABLE email_template_version');
        $this->addSql('DROP TABLE "user"');
    }
}
